FROM python:3.10-slim

WORKDIR /app
COPY pyproject.toml README.md /app/
COPY src /app/src

RUN pip install --no-cache-dir .

ENV CONNECTOR_TYPE=source
ENV AIRBYTE_ENTRYPOINT="yueshu-airbyte"
ENTRYPOINT ["yueshu-airbyte"]
