{
 "title": "5.X dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } },
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "graph_name", "label": "graph_name", "query": { "query": "label_values(graph_name)" } },
   { "name": "method", "label": "method", "query": { "query": "label_values(method)" } }
  ]
 },
 "panels": [
  { "title": "Graphd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "graphd_success_query",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "graphd_success_query{job=\"$job\", graph_name=\"$graph_name\"}"
    }
   ]
  },
  {
   "title": "graphd_error_query",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "graphd_error_query{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "graphd_query_latency_summary_5s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "graphd_query_latency_summary_5s{job=\"$job\", graph_name=\"$graph_name\"}"
    }
   ]
  },
  {
   "title": "graphd_query_latency_summary_5s_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "graphd_query_latency_summary_5s_count{graph_name=\"$graph_name\"}"
    }
   ]
  },
  {
   "title": "graphd_query_latency_summary_5s_sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "graphd_query_latency_summary_5s_sum{graph_name=\"$graph_name\"}"
    }
   ]
  },
  {
   "title": "graphd_total_sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    { "expr": "graphd_total_sessions\t" }
   ]
  },
  {
   "title": "graphd_active_sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    { "expr": "graphd_active_sessions" }
   ]
  },
  {
   "title": "graphd_dml_storage_client_latency_summary_5s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "graphd_dml_storage_client_latency_summary_5s{method=\"$method\"}"
    }
   ]
  },
  {
   "title": "graphd_dml_storage_client_latency_summary_5s_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "graphd_dml_storage_client_latency_summary_5s_count{method=\"$method\"}"
    }
   ]
  },
  {
   "title": "graphd_dml_storage_client_latency_summary_5s_sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "graphd_dml_storage_client_latency_summary_5s_sum{method=\"$method\"}"
    }
   ]
  },
  {
   "title": "graphd_dql_storage_client_latency_summary_5s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "graphd_dql_storage_client_latency_summary_5s{graph_name=\"$graph_name\", method=\"$method\"}"
    }
   ]
  },
  {
   "title": "graphd_dql_storage_client_latency_summary_5s_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "graphd_dql_storage_client_latency_summary_5s_count{graph_name=\"$graph_name\", method=\"$method\"}"
    }
   ]
  },
  {
   "title": "graphd_dql_storage_client_latency_summary_5s_sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "graphd_dql_storage_client_latency_summary_5s_sum{graph_name=\"$graph_name\", method=\"$method\"}"
    }
   ]
  },
  {
   "title": "graphd_cpu_percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    { "expr": "graphd_cpu_percentage" }
   ]
  },
  {
   "title": "graphd_memory_in_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    { "expr": "graphd_memory_in_bytes\t" }
   ]
  },
  { "title": "Meta", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "metad_rocksdb_latency_summary_5s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "metad_rocksdb_latency_summary_5s{method=\"$method\"}"
    }
   ]
  },
  {
   "title": "metad_rocksdb_latency_summary_5s_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "metad_rocksdb_latency_summary_5s_count{method=\"$method\"}"
    }
   ]
  },
  {
   "title": "metad_rocksdb_latency_summary_5s_sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "metad_rocksdb_latency_summary_5s_sum{method=\"$method\"}"
    }
   ]
  },
  {
   "title": "metad_cpu_percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    { "expr": "metad_cpu_percentage" }
   ]
  },
  {
   "title": "metad_memory_in_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "targets": [
    { "expr": "metad_memory_in_bytes" }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "storaged_success_query",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "storaged_success_query{method=\"$method\"}"
    }
   ]
  },
  {
   "title": "storaged_query_latency_summary_5s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "targets": [
    {
     "expr": "storaged_query_latency_summary_5s{method=\"$method\"}"
    }
   ]
  },
  {
   "title": "storaged_query_latency_summary_5s_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "storaged_query_latency_summary_5s_count{method=\"$method\"}"
    }
   ]
  },
  {
   "title": "storaged_query_latency_summary_5s_sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "targets": [
    {
     "expr": "storaged_query_latency_summary_5s_sum{method=\"$method\"}"
    }
   ]
  },
  {
   "title": "storaged_rocksdb_latency_summary_5s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "targets": [
    {
     "expr": "storaged_rocksdb_latency_summary_5s{method=\"$method\"}"
    }
   ]
  },
  {
   "title": "storaged_rocksdb_latency_summary_5s_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "targets": [
    {
     "expr": "storaged_rocksdb_latency_summary_5s_count{method=\"$method\"}"
    }
   ]
  },
  {
   "title": "storaged_rocksdb_latency_summary_5s_sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "targets": [
    {
     "expr": "storaged_rocksdb_latency_summary_5s_sum{method=\"$method\"}"
    }
   ]
  },
  {
   "title": "storaged_cpu_percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "targets": [
    { "expr": "storaged_cpu_percentage" }
   ]
  },
  {
   "title": "storaged_memory_in_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "targets": [
    { "expr": "storaged_memory_in_bytes" }
   ]
  }
 ]
}